# File: simple-param.yml
parameters:
- name: key # name of the parameter; required
  type: string # data type of the parameter; required
  default: ""

steps:
  - task: Cache@2
    inputs:
      key: 'composer | "$(Agent.OS)" | "${{ parameters.key }}" | composer.lock'
      path: $(COMPOSER_CACHE_DIR)
    displayName: Cache composer
