parameters:
- name: version # The version of composer to install
  type: string 
  default: ""

steps: 
- script: sudo composer self-update --${{ parameters.version }}
  displayName: Pin to Composer Version ${{ parameters.version }}