steps:
  - task: Cache@2
    inputs:
      key: 'composer | "$(Agent.OS)" | composer.lock'
      restoreKeys: |
        composer | "$(Agent.OS)"
        composer
      path: $(COMPOSER_CACHE_DIR)
    displayName: Cache composer
