variables:
  phpVersion: 7.2

trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Lint
  displayName: Lint
  steps:
  - template: templates/magento-auth.yml
  - template: templates/composer-install.yml
  - script: composer run-script lint
    displayName: Lint
- job: Unit_Test
  displayName: Unit Test
  steps:
  - template: templates/magento-auth.yml
  - template: templates/composer-install.yml
  - script: composer run-script unit-test
    displayName: Unit Test
- job: Integration_Test
  displayName: Integration Test
  strategy:
      matrix:
          php72_magento2.3:
            phpVersion: 7.2
            magentoTag: 2.3
          php73_magento2.3:
            phpVersion: 7.3
            magentoTag: 2.3
  steps:
  - template: templates/setup-php.yml
  - template: templates/magento-auth.yml
  - template: templates/integration-setup.yml
  - script: |
      cd $(pwd)/../magento2/dev/tests/integration
      ../../../vendor/bin/phpunit --testsuite "Graycore_Magento2Cors"
    displayName: Run Integration Tests
