trigger:
  branches:
    include:
    - master
    - develop
pr:
  autoCancel: true
  branches:
    include:
    - master
    - develop
variables:
  composer_config_cache: $(Pipeline.Workspace)/.npm
jobs:
  - job: Build
    displayName: Build And Test
    pool:
      vmImage: "Ubuntu 16.04"
    steps:
      - task: CacheBeta@0
        inputs:
          key: $(Build.SourcesDirectory)/composer.lock
          path: $(composer_config_cache)
        displayName: Cache Composer
  - job: Lint
    displayName: Lint
    pool:
      vmImage: "Ubuntu 16.04"
    strategy:
      matrix:
        node_10_x:
          node_version: 10.x
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: Set Node Version

      - task: CacheBeta@0
        inputs:
          key: $(Build.SourcesDirectory)/composer.lock
          path: $(composer_config_cache)
        displayName: Cache Composer

      - script: composer install
        displayName: Install Dependencies

      - script: composer run-script lint
        displayName: Lint
  - job: Integration_Test
  - job: Unit_Test
  - job: Api_Functional_Test