name: Create Release

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GRAYCORE_GITHUB_TOKEN }}
          command: manifest
          default-branch: master
